name: TestPlugin
version: 0.1
description: Testplugin zum probieren mit java-code
website: http://mclive.eu/
author: McLive
main: eu.mclive.testplugin.TestPlugin

commands:
  heile:
    description: Heilt den Spieler
    usage: /heile
    permission: testplugin.heile
  helptest:
    description: Hilfeseite
    usage: /heile
    permission: testplugin.heile
  haus:
    description: Haus setzen
    usage: /haus
    permission: testplugin.haus
  haustp:
    description: Nach Hause teleportieren
    usage: /haustp
    permission: testplugin.haustp